on:
  push:
    branches:
      - master






jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'before'
        run: pwd

      - name: 'printing folder contents'  
        run: ls

      - uses: actions/checkout@v3  

      - name: 'after'
        run: pwd


