on:
  push:
    branches: 
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  

      - name: 'login to docker hup'
        run: docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: 'building docker image'  
        run: docker build -t ${{ secrets.DOCKER_USER }}/dockerimage .

      - name: 'pushing to docker hup'  
        run: docker push ${{ secrets.DOCKER_USER }}/dockerimage




      

     